name: Bandit Scan

on:
  workflow_dispatch:
  push:
    paths:
      - 'codes.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install pandas bandit

      - name: Convert CSV to Python files
        run: |
          mkdir -p code_snippets
          python convert_csv.py

      - name: Run Bandit for CWE-20, CWE-22, CWE-200
        run: bandit -r code_snippets/ --tests B303,B304,B305,B506,B301,B604,B605,B102,B105,B106,B501,B502,B320 -f html -o bandit_report.html || true

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_report.html
