name: Semgrep CWE-20 Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run Semgrep with default security and Python rules
      - name: Semgrep scan with default rules
        run: semgrep --config=p/ci,p/python --output semgrep_default_report.json --json

      # Run Semgrep with your custom CWE-20 rule
      - name: Semgrep scan with custom CWE-20 rule
        run: semgrep --config=.github/semgrep --output semgrep_custom_report.json --json

      # Upload default report as artifact
      - name: Upload Semgrep Default Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-default-report
          path: semgrep_default_report.json

      # Upload custom report as artifact
      - name: Upload Semgrep Custom CWE-20 Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-custom-cwe20-report
          path: semgrep_custom_report.json
